### ISSUE TITLE
Cannt connect to  xclient

### ISSUE THREAD

**Issue by PangBaiWork** [khanhduytran0/ExagearAndroidX11Server#1]
This project looks great but I  couldnt  use it .
there are some errors when connect to proot linux of termux   (bad request?)
![Screenshot_20220502_134828](https://user-images.githubusercontent.com/63479821/166200529-959339ef-32d9-4ace-9efc-c5bbc90c2854.jpg)
Can you help me？

**Comment by ZhymabekRoman** [comment]
See README information:
```
While a client connect to, the X11 Server go to ANR (App Not Responding).
```

**Comment by xoureldeen** [comment]
What the port of x11?
I can fix this issue

**Comment by ZhymabekRoman** [comment]
This X11 implementation is from Exagear Windows emulator. Reverse engineered from closed sourced binaries. Do not use it because it doesn't work.

**Comment by xoureldeen** [comment]
> This X11 implementation is from Exagear Windows emulator. Reverse engineered from closed sourced binaries. Do not use it because it doesn't work.

Bro im done 😂
I can't find any good x11 source, pelya xsdl is mouse buggy and x11 termux when i unlock it for external apps it crash for no reason, i think i need to build my own source by xserver and sdl2 lol

**Comment by ZhymabekRoman** [comment]
@epicstudios856 I'm in the process of developing a new X11 Android implementation, it's very hard, but I'm still working on it.

Still have more problems than existing implementations, still working to get it to relase state. Maybe year or so on idk, lamo. 

See - https://github.com/ZhymabekRoman/android-xserver-enhanced

**Comment by xoureldeen** [comment]
I know thats xsdl java

Thats old and dosent support high apps and wm like awesome wm and xfce4 and wine or qemu,can i chat u about it bcuz i need an x11 for 
Vectras vm qemu based
Rpcs3 android port
Winux proton steam emulator

**Comment by ZhymabekRoman** [comment]
> I know thats xsdl java

Nope, that's not XSDL based backend.

> i chat u about it bcuz i need an x11 for

Feel free contribute

**Comment by xoureldeen** [comment]
root@localhost:~# xeyes
Error: Can't open display: 192.168.1.109:6000


Bruh, but official one is work

**Comment by xoureldeen** [comment]
Now i changed port and it works but dwm notwork, why

root@localhost:~# export DISPLAY=192.168.1.109:0
root@localhost:~# xeyes
Warning: locale not supported by C library, locale unchanged
X connection to 192.168.1.109:0 broken (explicit kill or server shutdown).
root@localhost:~# dwm
warning: no locale support
dwm: fatal error: request code=72, error code=8
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  72 (X_PutImage)
  Serial number of failed request:  58
  Current serial number in output stream:  63

**Comment by xoureldeen** [comment]
Ai repond:
request code=72, error code=8: This is a specific X11 error code. Request code 72 corresponds to X_PutImage, while error code 8, BadMatch, often indicates that some parameters provided do not match what is expected or allowed. This might happen if the depth, visual or class of the window does not match that of the pixmap, or if you are trying to perform an operation on a window with attributes that do not match the request.

4. Major opcode of failed request: 72 (X_PutImage): This further specifies that the failed request to the X server was an attempt to put an image onto the screen.

**Comment by ZhymabekRoman** [comment]
WIP - working in progress
